# Generated by Django 4.2.23 on 2025-06-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='order_date',
        ),
    ]
